# Generated by Django 2.2 on 2021-01-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Numbering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_image', models.ImageField(blank=True, help_text='Image shows with question.', null=True, upload_to='question_pic/')),
                ('question_title', models.CharField(help_text='Title of the projects', max_length=200)),
                ('option_one_image', models.ImageField(help_text='Option one image', upload_to='option_pics/')),
                ('option_two_image', models.ImageField(help_text='Option two image', upload_to='option_pics/')),
                ('option_three_image', models.ImageField(help_text='Option three image', upload_to='option_pics/')),
                ('option_four_image', models.ImageField(help_text='Option four image', upload_to='option_pics/')),
                ('question_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question_app.Numbering')),
            ],
        ),
    ]
