# Generated by Django 2.2 on 2021-01-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0002_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(help_text='Enter right answer - A,B,C,D', max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.OneToOneField(help_text="Question number can't be repeated.", on_delete=django.db.models.deletion.CASCADE, to='question_app.Numbering'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(help_text='Title of the question', max_length=200),
        ),
    ]
