# Generated by Django 2.2 on 2021-01-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0003_auto_20210109_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Enter right answer - A,B,C,D', max_length=1),
        ),
    ]
