# Generated by Django 2.2 on 2021-01-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0004_auto_20210111_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbering',
            name='question_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_four_image',
            field=models.ImageField(help_text='Option four image format-png/jpg', upload_to='option_pics/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_one_image',
            field=models.ImageField(help_text='Option one image format-png/jpg', upload_to='option_pics/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_three_image',
            field=models.ImageField(help_text='Option three image format-png/jpg', upload_to='option_pics/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_two_image',
            field=models.ImageField(help_text='Option two image format-png/jpg', upload_to='option_pics/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Image shows with question. format-png/jpg', null=True, upload_to='question_pic/'),
        ),
    ]
