# Generated by Django 2.2 on 2021-01-20 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_app', '0005_auto_20210118_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestent_answer', models.CharField(choices=[('S', 'S'), ('W', 'W'), ('R', 'R')], help_text='Enter right answer - A,B,C,D', max_length=1)),
                ('contestent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contestent_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Question')),
            ],
        ),
    ]
