# Generated by Django 2.2 on 2021-01-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0004_auto_20210111_1611'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='skip_quesiton',
            field=models.ManyToManyField(blank=True, to='question_app.Question'),
        ),
    ]
