# Generated by Django 2.2 on 2021-01-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_skip_quesiton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='skip_quesiton',
            new_name='skip_question',
        ),
    ]
