# Generated by Django 2.2 on 2021-01-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210113_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='skip_question',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Upload your profile pic in (png/jpg format only)', null=True, upload_to='profile_pic/'),
        ),
    ]
